version: "3"

services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      - app-network

  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - redis
      - db
    volumes:
      - ./:/var/www
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/supervisord/:/etc/supervisor/conf.d/
    networks:
      - app-network
    restart: always

  #Redis Service
  redis:
    container_name: redis
    image: 'redis:5-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - app-network
    restart: always

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: qdWWSaNBxPTdbfHp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local